apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: ctfd-service
spec:
  ports:
  - name: mysql-port
    port: 3301
    protocol: TCP
    targetPort: 3301
  selector:
    app: ctfd-service
  type: ClusterIP
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mysql
  labels:
    app: ctfd-demo
spec:
  selector:
    matchLabels:
      app: ctfd-demo
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ctfd-demo
        tier: mysql
    spec:
      containers:
      - name: mysql
        image: 'mysql:5.7'
        args:
            - "--ignore-db-dir=lost+found"
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secrets
                key: password
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: secrets
                key: username
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secrets
                key: password
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: secrets
                key: database
        ports:
        - containerPort: 3301
          name: mysql
        volumeMounts:
        - name: mysql-pv-claim
          mountPath: /var/lib/mysql/
      volumes:
      - name: mysql-pv-claim
        persistentVolumeClaim:
          claimName: mysql-pv-claim




        
